import = ["/Users/node/.config/alacritty/theme/one-dark.toml"]

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 2

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
y = 2

[window]
decorations_theme_variant = "Dark"
dynamic_padding = false
dynamic_title = true
option_as_alt = "Both"
opacity = 0.90
blur = true

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 10
y = 8
